services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "task"
      POSTGRES_USER: "elshadaghayev"
      POSTGRES_PASSWORD: "pg!dminPass"
      POSTGRES_PORT: 5432
    restart: always
    ports:
      - 5432:5432